### ISSUE TITLE
Create the consumer greeneyes_client.py

### ISSUE THREAD

**Issue by ghost** [CapivaraProjects/gykernel#4]
This script use the model loaded into a tensorflow_model_server to serve the result.
Following this example:
[tensorflow_serving/example/inception_client.py](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_client.py)

**Comment by WendelHime** [comment]
greeneyes_client should be here or GYResources?

**Comment by ghost** [comment]
You are right.  
Moved to [GYResources #105](https://github.com/CapivaraProjects/GYResources/issues/105)
